---
title: "Lab1"
author: "Clayton Curry"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Tasks

## Task 1

Find the working directory

```{r}
getwd()
```

## Task 2

```{r}
ddt <- read.csv("DDT.csv")
head(ddt)
```


## Task 3

  a. The qualitative variables are RIVER and SPECIES
  b. The quantitative variables are MILE, LENGTH, WEIGHT, DDT
  c. there are 3 unique values for species
```{r}
table(ddt$SPECIES)
```
  d. 
```{r}
ddtLMB800=with(ddt, ddt[WEIGHT>800 & SPECIES=="LMBASS",])
head(ddtLMB800)
```
  e.
```{r}
ddtSCM4=with(ddt, ddt[DDT>4.0 & RIVER=="SCM",])
head(ddtSCM4)
```

## Clicker Questions
  Q.1 Ans. 42.8125
```{r}
mean(ddt$LENGTH)
```
  Q.2 Ans. 376.5461
```{r}
sd(ddt$WEIGHT)
```
  Q3. 0
  
  Q4. 20/20 = 1
  
## Task 4
  a. 
```{r}
table(ddt$RIVER)
```
  
  b. 
  
```{r}
barplot(table(ddt$RIVER), col = 1:4)
```
  
  c.
  
```{r}
table(ddt$RIVER,ddt$SPECIES)
```
  
  d.
  
```{r}
barplot(table(ddt$RIVER,ddt$SPECIES), col = 1:5,horiz = TRUE,legend.text = TRUE)
```
  

## Task 5
  a.
  
```{r}
sp=with(ddt,table(SPECIES))
  pie(sp,col=1:3)
```
  
  b.
  
```{r}
sp=with(ddt,table(RIVER))
  pie(sp,col=1:4)
```
  
## Task 6
  a.
  
```{r}
boxplot(ddt$DDT)
```

  b. 
  
```{r}
boxplot(ddt$WEIGHT)
```

  c.
  
```{r}
boxplot(ddt$LENGTH)
```

## Task 7
  a.
  
```{r}
rivcol=with(ddt, ifelse(RIVER=="FCM","Red",
                        ifelse(RIVER=="LCM","Blue",
                               ifelse(RIVER=="SCM","Green","Black"))))
                    
  coplot(WEIGHT~LENGTH|RIVER,data=ddt,col=rivcol)
```

  b.
  
```{r}
fishcol=with(ddt,ifelse(SPECIES=="CCATFISH","Red",
                        ifelse(SPECIES=="SMBUFFALO","Blue","Green")))
coplot(WEIGHT~LENGTH|SPECIES,data=ddt,col=fishcol)
```
  
## Task 8

```{r}
library(dplyr)
library(ggplot2)

ddt %>% ggplot(aes(x=SPECIES,y=WEIGHT,fill=RIVER)) + geom_boxplot() + ggtitle("Clayton Curry")

ddt %>% ggplot(aes(x=RIVER,y=LENGTH,fill=SPECIES)) + geom_violin() + ggtitle("Clayton Curry")

ddt %>% ggplot(aes(x=WEIGHT,y=LENGTH,fill=SPECIES)) + geom_point() + ggtitle("Clayton Curry")

```

